services:
  nostalgiabot:
    build: .

    container_name: nostalgiaBot
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nostalgiabot.rule=Host(`nostalgiabot.ashhuston.com`)"
      - "traefik.http.routers.nostalgiabot.entrypoints=websecure"
      - "traefik.http.routers.nostalgiabot.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
